/*********************************************************************************************************
ClassName   : Constants
Description : Apex Class to store the common variables to be used in multiple codes.
Author      : Neha Dave

Version History :
Author      Date         Description
Neha Dave   05-07-2021   Initial Draft of constant class.
Neha Dave   05-07-2021   Added constant strings such as widget master etc.
**********************************************************************************************************/
public with sharing class Constants {
    public static final string WIDGET_EXECUTIVE_USER = 'Widget Executive';
    public static final string WIDGET_MASTER_USER = 'Widget Master';
}